identity:
    appId: mqtt
auth:
    key: a-j5sxd2-w8xfvanvkt
    token: 7ytglHN&OjkEZH)ZF?
options:
    domain: internetofthings.ibmcloud.com
    logLevel: debug
    mqtt:
        instanceId: instance1
        port: 1883
        transport: tcp
        cleanStart: true
        sessionExpiry: 7200
        keepAlive: 60